import { CACHED_BRIEFS } from "./cachedRegistry";
import type { GeneratedBrief } from "./generate";
import type { GeneratedGeneric } from "./generic";

export type CachedBriefFile = GeneratedBrief & { generic?: GeneratedGeneric };

// Committed output of scripts/generate-briefs.ts (cached mode, the default).
// The registry is regenerated by the script; an empty registry just means the
// app serves the deterministic fallback.

export function cachedBrief(scenarioId: string): CachedBriefFile | null {
  return (CACHED_BRIEFS[scenarioId] as CachedBriefFile | undefined) ?? null;
}

export function cachedScenarioIds(): string[] {
  return Object.keys(CACHED_BRIEFS).sort();
}
