// Generated by scripts/generate-prices.ts. Do not edit by hand.
import p_AUSHADH from "@/data/prices/AUSHADH.json";
import p_BRIGHTPATH from "@/data/prices/BRIGHTPATH.json";
import p_COASTBANK from "@/data/prices/COASTBANK.json";
import p_DHANVICON from "@/data/prices/DHANVICON.json";
import p_HINDMARK from "@/data/prices/HINDMARK.json";
import p_HINDMKLIFE from "@/data/prices/HINDMKLIFE.json";
import p_KESTREL from "@/data/prices/KESTREL.json";
import p_KIRTIENG from "@/data/prices/KIRTIENG.json";
import p_MERIDMOTOR from "@/data/prices/MERIDMOTOR.json";
import p_NSTARINFO from "@/data/prices/NSTARINFO.json";
import p_PRAKRITI from "@/data/prices/PRAKRITI.json";
import p_RANGOLI from "@/data/prices/RANGOLI.json";
import p_SAHYOGFIN from "@/data/prices/SAHYOGFIN.json";
import p_SKYREACH from "@/data/prices/SKYREACH.json";
import i_idx_auto from "@/data/indices/idx-auto.json";
import i_idx_bank from "@/data/indices/idx-bank.json";
import i_idx_capgoods from "@/data/indices/idx-capgoods.json";
import i_idx_consdur from "@/data/indices/idx-consdur.json";
import i_idx_conssvc from "@/data/indices/idx-conssvc.json";
import i_idx_energy from "@/data/indices/idx-energy.json";
import i_idx_finserv from "@/data/indices/idx-finserv.json";
import i_idx_fmcg from "@/data/indices/idx-fmcg.json";
import i_idx_it from "@/data/indices/idx-it.json";
import i_idx_market from "@/data/indices/idx-market.json";
import i_idx_pharma from "@/data/indices/idx-pharma.json";
import i_idx_telecom from "@/data/indices/idx-telecom.json";

export const PRICE_FILES: Record<string, unknown> = {
  "AUSHADH": p_AUSHADH,
  "BRIGHTPATH": p_BRIGHTPATH,
  "COASTBANK": p_COASTBANK,
  "DHANVICON": p_DHANVICON,
  "HINDMARK": p_HINDMARK,
  "HINDMKLIFE": p_HINDMKLIFE,
  "KESTREL": p_KESTREL,
  "KIRTIENG": p_KIRTIENG,
  "MERIDMOTOR": p_MERIDMOTOR,
  "NSTARINFO": p_NSTARINFO,
  "PRAKRITI": p_PRAKRITI,
  "RANGOLI": p_RANGOLI,
  "SAHYOGFIN": p_SAHYOGFIN,
  "SKYREACH": p_SKYREACH,
};

export const INDEX_FILES: Record<string, unknown> = {
  "idx-auto": i_idx_auto,
  "idx-bank": i_idx_bank,
  "idx-capgoods": i_idx_capgoods,
  "idx-consdur": i_idx_consdur,
  "idx-conssvc": i_idx_conssvc,
  "idx-energy": i_idx_energy,
  "idx-finserv": i_idx_finserv,
  "idx-fmcg": i_idx_fmcg,
  "idx-it": i_idx_it,
  "idx-market": i_idx_market,
  "idx-pharma": i_idx_pharma,
  "idx-telecom": i_idx_telecom,
};
