import corporateActionsJson from "@/data/corporateActions.json";
import { CorporateActionsFile, type PriceFile } from "@/lib/data/schemas";
import { generatePath, round2, type GeneratedPath } from "./engine";
import { INDEX_TARGETS, START, STOCK_TARGETS, T0 } from "./targets";

// Pure generation step (no file I/O) so tests can check determinism and that
// the committed files match what the generator produces.

export const MASTER_SEED = "before-you-buy/prices/v1";

export type GeneratedData = {
  indices: Record<string, PriceFile>;
  prices: Record<string, PriceFile>;
};

function toFile(id: string, dates: string[], prices: number[]): PriceFile {
  return {
    id,
    currency: "INR",
    adjusted: false,
    closes: dates.map((date, i) => ({ date, close: round2(prices[i]!) })),
  };
}

export function generateAll(): GeneratedData {
  const actions = CorporateActionsFile.parse(corporateActionsJson);
  const paths = new Map<string, GeneratedPath>();
  const indices: Record<string, PriceFile> = {};

  for (const t of INDEX_TARGETS) {
    const parent = t.parent ? paths.get(t.parent) : undefined;
    if (t.parent && !parent) throw new Error(`${t.id}: parent ${t.parent} must be generated first`);
    const path = generatePath({
      id: t.id,
      start: START,
      end: t.end,
      refDate: T0,
      refPrice: t.refPrice,
      annualVol: t.annualVol,
      parent: parent ? { path: parent, beta: t.beta } : undefined,
      anchors: t.anchors,
      seed: `${MASTER_SEED}/${t.id}`,
    });
    paths.set(t.id, path);
    indices[t.id] = toFile(t.id, path.dates, path.prices);
  }

  const prices: Record<string, PriceFile> = {};
  for (const t of STOCK_TARGETS) {
    const parent = paths.get(t.parent);
    if (!parent) throw new Error(`${t.ticker}: unknown parent ${t.parent}`);
    const path = generatePath({
      id: t.ticker,
      start: START,
      end: t.end,
      refDate: t.refDate,
      refPrice: t.refPrice,
      annualVol: t.annualVol,
      parent: { path: parent, beta: t.beta },
      anchors: t.anchors,
      seed: `${MASTER_SEED}/${t.ticker}`,
    });
    // The path is in adjusted terms. Raw quoted prices before a bonus/split
    // ex-date are higher by the share multiplier (dividends are not adjusted).
    const own = actions.filter((x) => x.companyId === t.companyId && x.shareMultiplier);
    const rawPrices = path.dates.map((date, i) => {
      let factor = 1;
      for (const act of own) {
        if (date < act.exDate) factor *= act.shareMultiplier!.after / act.shareMultiplier!.before;
      }
      return path.prices[i]! * factor;
    });
    prices[t.ticker] = toFile(t.ticker, path.dates, rawPrices);
  }
  return { indices, prices };
}

/** One close per line keeps diffs of the committed files readable. */
export function serialisePriceFile(file: PriceFile): string {
  const lines = file.closes.map((c) => `    ${JSON.stringify(c)}`);
  return [
    "{",
    `  "id": ${JSON.stringify(file.id)},`,
    `  "currency": "INR",`,
    `  "adjusted": false,`,
    `  "closes": [`,
    lines.join(",\n"),
    "  ]",
    "}",
    "",
  ].join("\n");
}

export function registrySource(data: GeneratedData): string {
  const ident = (s: string) => s.replace(/[^A-Za-z0-9]/g, "_");
  const priceIds = Object.keys(data.prices).sort();
  const indexIds = Object.keys(data.indices).sort();
  return [
    "// Generated by scripts/generate-prices.ts. Do not edit by hand.",
    ...priceIds.map((t) => `import p_${ident(t)} from "@/data/prices/${t}.json";`),
    ...indexIds.map((i) => `import i_${ident(i)} from "@/data/indices/${i}.json";`),
    "",
    "export const PRICE_FILES: Record<string, unknown> = {",
    ...priceIds.map((t) => `  ${JSON.stringify(t)}: p_${ident(t)},`),
    "};",
    "",
    "export const INDEX_FILES: Record<string, unknown> = {",
    ...indexIds.map((i) => `  ${JSON.stringify(i)}: i_${ident(i)},`),
    "};",
    "",
  ].join("\n");
}
