import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { generateBrief } from "@/lib/brief/generate";
import { generateGeneric } from "@/lib/brief/generic";
import { buildContextPack, isUnavailable } from "@/lib/contextPack/build";
import { glossary, scenarios } from "@/lib/data/load";
import { anthropicCaller, liveAvailable, modelId } from "@/lib/llm/client";
import { loadPrompt } from "@/lib/llm/prompts";

// Runs the brief pipeline for every scenario and writes data/briefs/<id>.json
// plus lib/brief/cachedRegistry.ts. These files are committed and served in
// cached mode.
//
//   npm run generate:briefs                 all scenarios (needs ANTHROPIC_API_KEY)
//   npm run generate:briefs -- --only=S01,S05
//   npm run generate:briefs -- --allow-fallback   write deterministic fallbacks when no key is set

const args = process.argv.slice(2);
const only = args.find((a) => a.startsWith("--only="))?.slice("--only=".length).split(",");
const allowFallback = args.includes("--allow-fallback");

if (!liveAvailable() && !allowFallback) {
  console.error("ANTHROPIC_API_KEY is not set. Set it, or pass --allow-fallback to write deterministic fallback briefs.");
  process.exit(1);
}

const root = process.cwd();
const dir = join(root, "data/briefs");
mkdirSync(dir, { recursive: true });

async function main(): Promise<void> {
  const rows: string[] = [];
  let fallbacks = 0;
  const targets = scenarios.filter((s) => s.surface === "stock" && (!only || only.includes(s.id)));

  for (const s of targets) {
    const out = await generateBrief(s.id, {
      llm: liveAvailable() ? anthropicCaller : null,
      systemPrompt: loadPrompt("brief-system"),
      glossary,
      now: () => new Date().toISOString(),
      serverFallback: true,
      requestedModel: liveAvailable() ? modelId() : null,
      log: (m) => console.log(`  ${m}`),
    });
    if ("unavailable" in out) {
      rows.push(`${s.id}  unavailable (no brief)`);
      continue;
    }
    // The research comparison arm (arm=generic) is generated from the same pack.
    const pack = buildContextPack(s.id);
    const generic = isUnavailable(pack)
      ? undefined
      : await generateGeneric(pack, {
          llm: liveAvailable() ? anthropicCaller : null,
          systemPrompt: loadPrompt("generic-explainer"),
          serverFallback: true,
        });
    writeFileSync(join(dir, `${s.id}.json`), JSON.stringify({ ...out, generic }, null, 2) + "\n");
    if (out.fallbackUsed) fallbacks++;
    const warnings = out.validation.results.filter((r) => !r.pass && r.severity === "warning").map((r) => r.rule);
    rows.push(
      `${s.id}  ${out.fallbackUsed ? "FALLBACK" : "ok      "}  attempts ${out.attempts.length}  served by ${out.servedModel ?? "—"}${warnings.length ? `  warnings ${warnings.join(",")}` : ""}${out.fallbackReason ? `  (${out.fallbackReason})` : ""}`,
    );
  }

  const files = existsSync(dir) ? readdirSync(dir).filter((f) => /^S\d{2}\.json$/.test(f)).sort() : [];
  const ident = (f: string) => f.replace(".json", "");
  writeFileSync(
    join(root, "lib/brief/cachedRegistry.ts"),
    [
      "// Generated by scripts/generate-briefs.ts. Do not edit by hand.",
      ...files.map((f) => `import ${ident(f)} from "@/data/briefs/${f}";`),
      "",
      "export const CACHED_BRIEFS: Record<string, unknown> = {",
      ...files.map((f) => `  ${ident(f)},`),
      "};",
      "",
    ].join("\n"),
  );

  console.log(rows.join("\n"));
  console.log(`\n${targets.length - fallbacks}/${targets.length} generated briefs passed validation; ${fallbacks} fell back.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
